version: '3.8'

services:
  web:
    image: my-app:latest
    environment:
      - NODE_ENV=staging
    ports:
      - "80:80"
    networks:
      - webnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
